name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'master'
      - 'zowe-v1-lts'

jobs:
  build:

    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: docker://github/super-linter:v3
      env:
        LINTER_RULES_PATH: .
        TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
        VALIDATE_JSON: true
        VALIDATE_MD: true
        VALIDATE_TYPESCRIPT_ES: true
